FROM alpine:3

RUN apk add build-base vips-dev
# RUN apk add build-base vips-dev && \
#    wget -O - https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2 | tar -xj && \
#    cd jemalloc-5.3.0 && \
#    ./configure && \
#    make && \
#    make install

WORKDIR /app

COPY . ./

RUN make

# ENV LD_PRELOAD=/usr/local/lib/libjemalloc.so.2
ENTRYPOINT ["/usr/bin/time", "-v", "/app/cvips"]
