FROM alpine:3

RUN apk add gcc musl-dev go vips-dev
WORKDIR /app

# Retrieve application dependencies.
# This allows the container build to reuse cached dependencies.
# Expecting to copy go.mod and if present go.sum.
COPY go.* ./
RUN go mod download

# Copy local code to the container image.
COPY . ./

# Build the binary.
RUN go build -v -o server

# Run the web service on container startup.
WORKDIR "/app"
ENTRYPOINT ["/usr/bin/time", "-v", "/app/server"]
